### PR TITLE
 	Replace OpenSSL by mbedtls, better multi-platform support, small program size, no dependencies.  	Script for mingw32 cross-compile.

### PR DESCRIPTION
**Pull request by javimadgit**

### CODE REVIEW

**Comment by socram8888** [comment]
Thanks! I've merged it on a seperate branch (#4184aedd74390e74d1d5d9c31d4b56468658b725) and will be mantaining both.

I kinda like the OpenSSL one, as it depends on system's library (so it should be always up to date) and program size is smaller (if we exclude the library, that is). I'll probably deprecate the OpenSSL one if I manage to dynamically link mbedtls, though.

**Comment by jedahan** [comment]
This fork worked well on osx. Didn't know how to setup ccmake to look in the correct places for my homebrew-installed openssl headers and libraries

**Comment by socram8888** [comment]
Hah, fun fact: I've begun a few hours ago to merge this with master, and drop the original branch that depends on OpenSSL, because compiling with the last under Windows is a pain in the ass.

**Comment by socram8888** [comment]
I've just pushed a new commit to master with mbedTLS in place of OpenSSL. Unlike this PR, I've added mbedTLS as a submodule.

Also, I've dropped CMake in favor of Makefile, which is easier to use under msys for releasing Windows versions.

**Pull request closed without merging**
