### PR TITLE
Add a quick and dirty python decoder

### PR DESCRIPTION
**Pull request by ynsta**
Quick and Dirty python tool used to decode amiibo content

Can be chained with amiitool:
./amiitool -k keys.bin -d -i amiibo.bin | ./amiidecode.py -k keys.bin

Signed-off-by: Stany MARCEL <stanypub@gmail.com>

### CODE REVIEW

**Comment by socram8888** [comment]
I'm not sure this repository is the best place for a Python implementation - IMHO that should go in another repo, probably as a library so it can be reused by other developers (unlike this amiitool thing which I never worked around making it a proper standalone library)

**Comment by ynsta** [comment]
I proposed it as an external tool that can decode the output of amiitool, I used it to understand data format. And Implement the copy function.

Python is nice to do quick prototyping things like that, but I agree that ideally a function in amiitool that permit to map/decode and re-encode a detailed structure would be nice.

I leave my python script in a fork if someone is interested in the decoding work I started.

**Comment by socram8888** [comment]
Actually rather than hacking amiitool for that I meant more like porting the whole thing to Python - I only did this in C because that's what I preferred to use back then, but it would be more useable for most developers in a higher level language.

I'll see if this summer I have so free time to work on it.

**Comment by ynsta** [comment]
It might be interesting to keep a "low level" library that can be embedded in applications written in other language like android/java or python.

For this purpose C is a good choice as almost any language has the possibility to bind with it.

For example the TagMo android application use a copy of amiitool https://github.com/Kidel/TagMo/tree/master/ndk/jni.

**Pull request closed without merging**
